#!/bin/sh

autoload -U promptinit; promptinit
prompt spaceship

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/kennymcavoy/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/kennymcavoy/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/kennymcavoy/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/kennymcavoy/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

alias pwdE='printf "%q\n" "$(pwd)"'
alias la='ls -la'
