#!/bin/sh

# Update functions? Haven't tested
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# ls alias
alias ls='ls -G'
alias la='ls -laG'

# print pwd with escapes
alias pwdE='printf "%q\n" "$(pwd)"'

# Easy edit zsh configs
alias zshconfig="nvim $ZDOTDIR/.zshrc"
alias zshdir="cd $ZDOTDIR"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# Unused
# alias j='z'
# alias f='zi'
# alias g='lazygit'
# alias nvimrc='nvim ~/.config/nvim/'
# alias lvim='nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim"'

# get top process eating memory
# alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
# alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# alias m="git checkout master"
# alias s="git checkout stable"
